version: "3.8"

services: 
    # config-service:
    #     image: frtande/config-server
    #     container_name: config-service
    #     ports: 
    #       - "8888:8888"
        # networks: 
        #     my-network:
        #         ipv4_address: 172.16.238.10             
    eureka-service:
        image: frtande/eureka-server
        container_name: eureka-service
        ports: 
          - "8761:8761"
        # networks: 
        #     - my_network 


networks:
    default:
        external:
            name: my_network        
#networks: 
#    my-network:
#        ipam:
#            driver: default
            # config:
            #     - subnet: "172.16.238.0/24"
            